language: swift
os: osx
osx_image: xcode10
xcode_project: QRCode.xcodeproj

matrix:
  include:
    - name: "macOS"
      xcode_scheme: QRCode_macOS
    - name: "iOS"
      xcode_scheme: QRCode_iOS
    - name: "macOS Example App"
      xcode_scheme: Example_macOS
    - name: "iOS Example App"
      xcode_scheme: Example_iOS
